src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\DocumentRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Entity\User;



/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 * @UniqueEntity("numdocument")
 */
class Document
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     * @Assert\NotBlank
     */
    private $numdocument;

    /**
     * @ORM\ManyToOne(targetEntity=TypeDocument::class, inversedBy="documents")
     * @Assert\NotBlank
     */
    private $nomdocument;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    
    private $information;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $commentaire;

     /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(groups={"new"} ,message="Merci de mettre une image !")
     */
    private $ImageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="documents")
     */
    private $Createdby;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="EditDoc")
     */
    private $Editby;

  

    public function __construct()
    {
     
        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
     
        
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumdocument(): ?string
    {
        return $this->numdocument;
    }

    public function setNumdocument(string $numdocument): self
    {
        $this->numdocument = $numdocument;

        return $this;
    }

    public function getInformation(): ?string
    {
        return $this->information;
    }

    public function setInformation(string $information): self
    {
        $this->information = $information;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getNomdocument(): ?typedocument
    {
        return $this->nomdocument;
    }

    public function setNomdocument(?typedocument $nomdocument): self
    {
        $this->nomdocument = $nomdocument;

        return $this;
    }

 

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;
        
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getImageFile(): ?string
    {
        return $this->ImageFile;
    }

    public function setImageFile(string $ImageFile): self
    {
        $this->ImageFile = $ImageFile;

        return $this;
    }

    public function getCreatedby(): ?user
    {
        return $this->Createdby;
    }

    public function setCreatedby(?user $Createdby): self
    {
        $this->Createdby = $Createdby;

        return $this;
    }

    public function getEditby(): ?User
    {
        return $this->Editby;
    }

    public function setEditby(?User $Editby): self
    {
        $this->Editby = $Editby;

        return $this;
    }

   
   

    



   

}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use App\Entity\TypeDocument;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numdocument', TextType::class, array('label' => 'N° Document'),)
            ->add('nomdocument',EntityType::class, array(
                'label' => 'Nom Document',
                'class' => TypeDocument::class,
                'choice_label' => 'description'))
            //->add('imageFile',FileType::class,array('label' => 'image png ou jpeg', 'data_class'=> null))
            ->add('ImageFile', FileType::class, [
                'label' => 'Document (PDF file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger un document PDF valide',
                    ])
                ],
            ])
            ->add('information', TextType::class, array('label' => 'Information'),)
            ->add('commentaire', TextareaType::class, array('label' => 'Commentaire'),)
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Entity\User;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;

class DocumentController extends AbstractController
{

    /**
     *  @var DocumentRepository
     */
    private $repository;

    public function __construct(DocumentRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/doc", name="document_index")
     */
    public function index(): Response
    {
        
        $document = $this->repository->findAll();
       
        return $this->render('document/index.html.twig', [
            'document' => $document,
           
        ]);
        

      
    }

    /**
     * @Route("document/add",name="document_add")
     */

    public function add(Request $request)
    {
        $Document = new Document();
        $form = $this->createForm(DocumentType::class, $Document);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
       
        $user = $this->getUser();
         
            /** @var UploadedFile $ImageFile */
            $ImageFile = $form->get('ImageFile')->getData();            
            if ($ImageFile) {
              
                $newFilename = md5(uniqid()) . '.' . $ImageFile->guessExtension();  
                try {
                    $ImageFile->move(
                        $this->getParameter('brochures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) { }

                $Document->setImageFile($newFilename);
            }

            $em = $this->getDoctrine()->getManager();
            
            $Document->setCreatedby($user);
             
            $em->persist($Document);
            $em->flush();
            $this->addFlash('success', 'Bien ajoutè avec succès ');
            return $this->redirectToRoute('document_index');
        }
        return $this->render('document/add.html.twig', [
            'Document' => $Document,
                
            'form' => $form->createView(),
           
            
        ]);
    }

    /**
     * @Route("document/edit/{id}" , name="document_edite")
     */

    public function edit(Document $document, Request $request, CacheManager $cacheManager, UploaderHelper $helper)
    {

        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
             /** @var UploadedFile $ImageFile */
             $ImageFile = $form->get('ImageFile')->getData();
             $document->setUpdatedAt(new \DateTime());
            
             if ($ImageFile) {
               
                 $newFilename = md5(uniqid()) . '.' . $ImageFile->guessExtension();  
                 try {
                     $ImageFile->move(
                         $this->getParameter('brochures_directory'),
                         $newFilename
                     );
                 } catch (FileException $e) { }
 
 
                 $document->setImageFile($newFilename);
             }




            $em = $this->getDoctrine()->getManager();
             
            $document->setEditby($user);
            
            
            
            $em->flush();
            $this->addFlash('success', 'Bien modifié avec succès ');
            return $this->redirectToRoute('document_index');
        }

        return $this->render('document/edit.html.twig', [
            'document' => $document,
            'form' => $form->createView(),
        ]);
    }

    /**
     *
     * @Route("/{id}", name="document_delete", methods="DELETE")
     */
    public function Delete(Document $document, Request $request)
    {
        if ($this->isCsrfTokenValid('delete' . $document->getId(), $request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();

            $em->remove($document);
            $em->flush();
            $this->addFlash('success', 'Bien supprimé avec succès ');
        }
        return $this->redirectToRoute('document_index');
    }

  /**
     * @Route("/", name="totalDoc")
     */
    public function total() :Response
    {   if ($this->isGranted('ROLE_ADMIN')){
        $total = $this->repository->findTotatldoc();    
        $totalparjrs = $this->repository->findDocJrs(new \DateTime);
        $totalEtude = $this->repository->findDocTypeEtude();
        $totalRC = $this->repository->findDocTypeRC();
        $totalPV = $this->repository->findDocTypePV();
        $totalFacture = $this->repository->findDocTypeFacture();
        $totalparmois = $this->repository->findDocparMois();
        $totalparannees = $this->repository->findDocparAnnees();
        
        return $this->render('document/stati.html.twig',[
        'total'=>$total,
        'totalparjrs' =>$totalparjrs,
        'totalEtude' =>$totalEtude,
        'totalRC' =>$totalRC,
        'totalPV' =>$totalPV,
        'totalFacture' =>$totalFacture,
        'totalparmois'=>$totalparmois,
        'totalparannees' =>$totalparannees,
         ] );
        }

        else
        {
            return $this->redirectToRoute('document_index');
        }
    }


}

templates/document/add.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}
        {% block stylesheets %}{% endblock %}

{% block body %}
<div class="container mt-4">
 <div class="col-xs-10">

   
 {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
 {{ form_rest(form) }}

<form >
    <div class="row" >
    
        <div >
        
         {{ form_row(form.numdocument) }}

        </div>

        <div >
            {{ form_row(form.information) }}
        </div>
         <div >
            {{ form_row(form.commentaire) }}
        </div>
         <div >
            {{ form_row(form.nomdocument) }}
        </div>
        <div >
       
            {{ form_row(form.ImageFile)}}
        </div>
        
    </div>

    
    <div>
      <button type="submit" class="btn btn-primary mb-2">Enregistre
    </div>

</div>

</form>
 </div>  

 {% block javascripts %}
 <script>

$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
 {% endblock %}
{% endblock %}

templates/document/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Documents {% endblock %}
{% block body %}
<div class="container mt-4">
 <div class="col-xs-10">
   
 {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
 {{ form_widget(form) }}

<form>
    
    <div class="row">
    
        <div class="col">
            {{ form_row(form.numdocument) }}

        </div>

        <div class="col">
            {{ form_row(form.information) }}
        </div>
         <div class="col">
            {{ form_row(form.commentaire) }}
        </div>
         <div class="col">
            {{ form_row(form.nomdocument) }}
        </div>
        <div class="col">
            {{ form_row(form.ImageFile) }}
        </div>
        
    </div>

    
    <div>
      <button type="submit" class="btn btn-primary mb-2">Modifier
    </div>

</div>
</form>
   </div>
   </div>
  {% block javascripts %}
 <script>

$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
 {% endblock %}
{% endblock %}

templates/document/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}
	
   {% block stylesheets %}
 
   
   {% endblock %}

{% block body %}
	<div class="container">
   {% for message in app.flashes('success') %}
 <div class="alert alert-success alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Success!</strong>  {{ message }}
  </div>
{% endfor %}
   
      
<div>
    <table class="table table-hover dt-responsive nowrap" style="width:100%" id="tables">
        <thead >
        
            <tr >
            
                <th ></th>
                <th >N° document</th>
            
                
             
                <th >Nom Document</th>
                <th >Ajouter Par</th>
                <th >Date Création</th>
                <th >Modifier Par</th>
                <th >Date Modification</th>
                
                <th >Actions</th>

                <th >Information</th>
                <th >Commentaire</th>
                
            </tr>
        </thead>
        <tbody>
        {% for d in document %}
       

            <tr class="table-Default">
             
              
             <td> <a href="{{ asset('images/documents/' ~ d.imageFile) }}"  target="_blank"><img src="img/fileicon.png"></a> 
            
             </td>
                <td>{{ d.numdocument }}</td>
               
               <td>{{ d.nomdocument }}</td>
               <td>{{ d.createdby }}</td>
                <td>{{ d.CreatedAt|date("d/m/Y")  }}</td>
               <td>{{ d.editby }}</td>
               <td>{{ d.UpdatedAt|date("d/m/Y")  }}</td>
               
               
              
                
                <td>
                    
                    <button ><a href="{{ path('document_edite',{id: d.id})  }} " ><img src="img/edit.png"></a></button>
                    <form method="post" action="{{ path('document_delete',{id: d.id})}}" 
                    style="display:inline-block"
                    onsubmit="return confirm('Etes vous vraiment sur ?')">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ d.id)}}">
                    <button ><img src="img/remove.png"></button>
                    </form>
                    
                </td>
             <td>{{ d.information }}</td>
               <td>{{ d.commentaire }}</td>    
           

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% block javascripts %}
   
{% endblock %}

            
            <a href="{{ path('document_add') }}" class="btn btn-success">Importe un nouveau document</a>
            
   </div>
   </div>


{% endblock %}

templates/document/stati.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}
	
   {% block stylesheets %}

   
   {% endblock %}

{% block body %}
<ol class="breadcrumb purple lighten-4">
    <img src="\img\doc.png"> <li class="breadcrumb-item active">Statistique des documents ajoutés</li>
 </ol>

        
	   <div class="row">

                <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body media-body text-right">
                                    {% for t in total %}
                                     <div class="h2 mb-0 font-weight-bold text-gray-800">
                                 {{ t.total }}
                                    </div>
                                    </div>
                                    {% endfor %}
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <div class="small text-white"><img src="\img\total.png"></div>
                                        <i>Total</i>
                                    </div>
                                </div>
                            </div>


                  <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body media-body text-right">
                                    {% for tjrs in totalparjrs %}
                                     <div class="h2 mb-0 font-weight-bold text-gray-800">
                                 {{ tjrs.totalparjrs }}
                                    </div>
                                    </div>
                                    {% endfor %}
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <div class="small text-white"><img src="\img\day.png"></div>
                                        <i>Par Jour</i>
                                    </div>
                                </div>
                            </div>


                    <div class="col-xl-3 col-md-6">
                                <div class="card bg-secondary text-white mb-4">
                                    <div class="card-body media-body text-right">
                                    {% for tmpois in totalparmois %}
                                     <div class="h2 mb-0 font-weight-bold text-gray-800">
                                 {{ tmpois.totalparmois }}
                                    </div>
                                    </div>
                                    {% endfor %}
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <div class="small text-white"><img src="\img\month.png"></div>
                                        <i>Par Mois</i>
                                    </div>
                                </div>
                            </div>

                    <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body media-body text-right">
                                    {% for tyear in totalparannees %}
                                     <div class="h2 mb-0 font-weight-bold text-gray-800">
                                 {{ tyear.totalparannees }}
                                    </div>
                                    </div>
                                    {% endfor %}
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <div class="small text-white"><img src="\img\year.png"></div>
                                       <i> Par Année </i>
                                    </div>
                                </div>
                            </div>
  </div>
         

     <div id="piechart"></div>
        
      


{% block javascripts %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

   <script>
    google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

// Draw the chart and set the chart values
function drawChart() {
  var data = google.visualization.arrayToDataTable([
     

 
  ['Task', 'Hours per Day'],
  {% for E in totalEtude %} ['Etude', {{ E.Etude }}]  {% endfor %},
  {% for P in totalPV %} ['PV',  {{ P.PV }}] {% endfor %},
  {% for R in totalRC %} ['RC',  {{ R.RC }}] {% endfor %},
  {% for F in totalFacture %}  ['Facture',  {{ F.Facture }}] {% endfor %},
  
]);

  // Optional; add a title and set the width and height of the chart
  var options = {'title':'Documents Par Type', 'width':800, 'height':600};

  // Display the chart inside the <div> element with id="piechart"
  var chart = new google.visualization.PieChart(document.getElementById('piechart'));
  chart.draw(data, options);
}
   </script>
{% endblock %}
            

{% endblock %}